all:
  children:
    windows:
      hosts:
        srv01:
          ansible_host: 10.10.10.20
          ansible_connection: winrm
          ansible_port: 5985
          ansible_user: Administrator
          ansible_password: "{{ vault_srv01_password }}"
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
        dc01:
          ansible_host: 10.10.10.10
          ansible_connection: winrm
          ansible_port: 5985
          ansible_user: Administrator
          ansible_password: "{{ vault_dc01_password }}"
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore

